// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // O CLI usa uma conexão persistente (Session pooler ou conexão direta).
    // A aplicação continua usando DATABASE_URL pelo adapter em repositories/client.ts.
    url: env("DIRECT_URL"),
  },
});
